In [6]:
import numpy as np

a = np.arange(1, 11)
print(a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data type:", a.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data type: int64


In [7]:
I = np.eye(3)
print(I)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
z = np.zeros((2, 4))
o = np.ones((3, 2))
print(z)
print(o)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
x = np.linspace(0, 1, 10)
print(x)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
arr = np.array([4, 7, 1, 9, 3])
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())


Sum: 24
Mean: 4.8
Max: 9


In [ ]:
a = np.arange(10, 50, 2).reshape(4, 5)
print(a)

print(a[:, 2])

print(a[1, :])

a[a > 30] = -1
print(a)


[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
[14 24 34 44]
[20 22 24 26 28]
[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(a[1:3, 1:4])

print(a[a > 6])


[[ 6  7  8]
 [10 11 12]]
[ 7  8  9 10 11 12]


In [13]:
m = np.random.randint(1, 100, (5, 5))
print(m)

print("Row max:", m.max(axis=1))
print("Column min:", m.min(axis=0))


[[ 1 88 65 87 18]
 [19 53 66 54 69]
 [42 17 35 87 27]
 [28 31 48 71 18]
 [94 16 31 99 69]]
Row max: [88 69 87 71 99]
Column min: [ 1 16 31 54 18]


In [14]:
a = np.array([5, 10, 15])

print(a + 100)
print(a * 2)


[105 110 115]
[10 20 30]


In [15]:
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
scores = np.array([126, 115, 130, 141, 132])

print(scores[scores < 130])
print(scores[names == "Statira"])
scores[names == "Roxana"] += 10
print(scores)


[126 115]
[115 141]
[136 115 140 141 142]


In [ ]:
m = np.array([[10, 25, 30], 
              [5, 18, 40]])

print(m > 20)


[[False  True  True]
 [False False  True]]


In [17]:
a = np.arange(2, 42, 2).reshape(4, 5)
print(a)


[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [18]:
r1 = np.full((1, 4), -1)
r2 = np.zeros((1, 4))
r3 = np.full((1, 4), 2)

v = np.vstack((r1, r2, r3))
print(v)


[[-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 2.  2.  2.  2.]]


In [19]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n", A + B)
print("Matrix multiplication:\n", A @ B)


Addition:
 [[ 6  8]
 [10 12]]
Matrix multiplication:
 [[19 22]
 [43 50]]


In [20]:
m = np.random.randint(1, 50, (4, 4))
print(m)

print("Row sum:", m.sum(axis=1))
print("Column mean:", m.mean(axis=0))
print("Max:", m.max())
print("Min:", m.min())


[[18 20 22 47]
 [23  9  3  3]
 [28 19 18 47]
 [44 33 23  2]]
Row sum: [107  38 112 102]
Column mean: [28.25 20.25 16.5  24.75]
Max: 47
Min: 2
